kind: pipeline
name: default

steps:
- name: docker-condo
  image: banzaicloud/drone-kaniko
  settings:
    username: 
      from_secret: docker-hub-username
    password: 
      from_secret: docker-hub-password
    build_args:
      from_secret: build-args
    repo: kramergroup/casm
    tags: 
    - condo-latest
    - condo-${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile
- name: docker-minimal
  image: banzaicloud/drone-kaniko
  settings:
    username: 
      from_secret: docker-hub-username
    password: 
      from_secret: docker-hub-password
    build_args:
      from_secret: build-args
    repo: kramergroup/casm
    tags: 
    - latest 
    - minimal-latest
    - minimal-${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile.minimal