kind: pipeline
name: default

steps:
- name: docker-build
  image: banzaicloud/drone-kaniko
  settings:
    username: 
      from_secret: docker-hub-username
    password: 
      from_secret: docker-hub-password
    repo: kramergroup/casm
    dockerfile: Dockerfile